  name: ci-example-golang-workflow
  on:
    pull_request:
        branches:
            - develop
  jobs:
    check-application:
      runs-on: ubuntu-latest
      if: always()
      strategy:
        matrix:
          go: ['1.20','1.21.1']
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}
        - run: go test
        - run: go run math.go
    tests:
      runs-on: ubuntu-latest
      needs: check-application
      if: always()
      steps:
        - name: All tests ok
          if: ${{ !(contains(needs.*.result, 'failure')) }}
          run: exit 0
        - name: Some tests failed
          if: ${{ contains(needs.*.result, 'failure') }}
          run: exit 1
