  name: ci-example-golang-workflow
  on:
    pull_request:
        branches:
            - develop
  jobs:
    check-application:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          go: ['1.20','1.21.1']
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}
        - run: go test --coverprofile=coverage.out
        - run: go run math.go


        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: leothenardo/goapp123:latest


    tests:
      runs-on: ubuntu-latest
      needs: check-application
      if: always()
      steps:
        - name: All tests ok
          if: ${{ !(contains(needs.*.result, 'failure')) }}
          run: exit 0
        - name: Some tests failed
          if: ${{ contains(needs.*.result, 'failure') }}
          run: exit 1
