  name: ci-example-golang-workflow
  on:
    pull_request:
        branches:
            - develop
  jobs:
    check-application:
      runs-on: ubuntu-latest
      name: Go ${{ matrix.go }} sample
      strategy:
        matrix:
          go: ['1.20','1.21.1']
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}
        - run: go test
        - run: go run math.go